### PR TITLE
Add Docker support

### PR DESCRIPTION
**Pull request by drkno**
Awesome project!

This adds a Dockerfile, enabling it to run as a docker container.

To build: `docker build --no-cache -t cjmanca/plex-credits-detect .`
To run: `docker run --rm -v /some/config/path:/config -it cjmanca/plex-credits-detect:latest`

Only tested on Linux, but should work anywhere Linux based Docker containers work.

If you want this to build using pipelines, that is also possible with a config similar to this one: https://github.com/drkno/PlexSSOv2/blob/master/.github/workflows/docker-publish.yml

### CODE REVIEW

**Comment by cjmanca** [comment]
Great, thanks! I really need to learn docker someday, seems like it's what all the cool kids are using!

So it worked in Linux then? Was able to find fingerprints fine?

**Comment by cjmanca** [comment]
While attempting to test this, I ran across an issue that I'm hoping you'll have an answer for. It seems to work fine while the Plex Server is stopped, but if plex is running I get an IO error that looks to be related to sqlite locking. Google suggests using the "nobrl" option, but being the docker newb that I am, I can't figure out how to do that. Is there a way to specify that in the dockerfile?

**Comment by drkno** [comment]
It seemed to work fine for me on my runs of it on Linux, however I intend to try and deploy it less temporarily on my existing stack. If I encounter the same issue I'll let you know (and probably patch it).

**Comment by cjmanca** [comment]
May only be an issue with running the docker container on windows with a native windows version of the plex media server. I had to do a bunch of changes to the source to properly support mapping paths due to the different directory structure to get it to work at all.

**Pull request merged**
